server: 
  port: 8081
  
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

store:
  uri: https://store.playstation.com/pt-br/grid/STORE-MSF77008-ALLGAMES/
  firstPage: 230
  defaultTotalPages: 235
